title: Dr. Philipp Müller
logo: images/pm.jpg
description: Interim Professor in the Institute for Media and Communication Studies, University of Mannheim, Germany
show_downloads: false
theme: jekyll-theme-minimal