title: Dr. Philipp Müller
logo: images/pm.jpg
description: Senior Lecturer in the Institute for Media and Communication Studies at University of Mannheim, Germany
show_downloads: false
theme: jekyll-theme-minimal